GROUND_TRUTH_FOLDER = "./ground-truth"

#  Matching names used in ESMI location information .csv
# LOCATIONS_IN_UTTAR_PRADESH = [
#     "Agarwal Mohalla Jarwal Kasba",
#     "Aishbagh-Lucknow",
#     "Alambagh- Lucknow",
#     "Aliganj- Lucknow",
#     "Allipur-Fatehpur",
#     "Anand Nagar Sitapur",
#     "Arjun Nagar-Ghaziabad",
#     "Ashiana-Lucknow [Offline]",
#     "Awas Vikas colony Barabanki",
#     "Bag Kala Lan Saharanpur [Offline]",
#     "Bahadurpur-Bahraich",
#     "Baraulia-Barabanki",
#     "Bardaha-Bahraich",
#     "Bari Bag Saharanpur",
#     "Barra 2- Kanpur [Offline]",
#     "Barra - Kanpur [Offline]",
#     "Bashirganj Bahraich",
#     "Belhara-Barabanki [Offline]",
#     "Bhadupur Sidhauli",
#     "Bhagrahan Tola Nanpara [Offline]",
#     "Bhairav Talab - Varanasi [Offline]",
#     "Bhattha Mehmoodabad",
#     "Bhavaniyapur Baharaich," "Bhupauli-Chandauli [Offline]",
#     "Birhana Road- Kanpur [Offline]",
#     "Biswan-Sitapur",
#     "Brandawan-Barabanki",
#     "Chakia- Chandauli [Offline]",
#     "Chirgaon-Jhansi [Offline]",
#     "Chowk Bazar Jarwal Kasba",
#     "Chunaitee Gara-Saharanpur",
#     "Civil Line- Kanpur [Offline]",
#     "Civil line-Fatehpur",
#     "Civil lines Jhansi [Offline]",
#     "Dariyabad-Barabanki",
#     "Dashehrabagh Barabanki",
#     "Daudpur- Chandauli [Offline]",
#     "Devtapur-Sitapur[Offline]",
#     "Dhaneja- Chandauli [Offline]",
#     "Dhanoli Agra",
#     "Dhanwa Ramsahaypurwa Bahraich [Offline]",
#     "Dharampur",
#     "Fatehpur-Barabanki",
#     "Firozpur Suratganj",
#     "Ganeshpur-Barabanki",
#     "Ghulam Ali Pura Bahraich",
#     "Gondaura-Barabanki",
#     "Haidergarh-Barabanki",
#     "Haqikatnagar Saharanpur",
#     "Harsinghpur-Fatehpur [Offline]",
#     "Housila Nagar Faizabad",
#     "Husepur-Fatehpur",
#     "Huzurpur road-Kaisarganj",
#     "Huzurpur-Bahraich",
#     "Hydel Colony Jhansi [Offline]",
#     "Ibrahimpur-Barabanki",
#     "Ichauli- Sitapur",
#     "Inayat Nagar-Faizabad",
#     "Indirapuram- Ghaizabad",
#     "Jagatapur-Bahraich",
#     "Jahanabad-Fatehpur [Offline]",
#     "Jankipuram Lucknow",
#     "Jayapur- Varanasi [Offline]",
#     "Jhar Pahar Jhansi",
#     "Jhauwa Khurd- Sitapur",
#     "Jhundapura-Noida",
#     "Jyotishah Alampur- Sitapur [Offline]",
#     "Kadirabag 1 Ramnagar",
#     "Kakadeo-Kanpur",
#     "Kamhira Kathura - Sitapur",
#     "Kanjaya-Bahraich",
#     "Kanjwara-Barabanki",
#     "Kankari- Sitapur",
#     "Kanoongopura Bahraich",
#     "Kapoorthala-Lucknow",
#     "Karsanda-Barabanki",
#     "Kasraila-Barabanki",
#     "Kedar Nagar Agra",
#     "Kevai-Fatehpur",
#     "Khaga-Fatehpur [Offline]",
#     "Khindaura- Sitapur",
#     "Khutehna-Bahraich [Offline]",
#     "Kotwa Dham-Barabanki [Offline]",
#     "Kuchera-Faizabad [Offline]",
#     "Kumarheda-Saharanpur [Offline]",
#     "Kurmaura-Bahraich",
#     "Loha Mandi Jhansi [Offline]",
#     "Mahasi-Bahraich",
#     "Mahawan-Faizabad",
#     "Manwan- Sitapur",
#     "Masvanpur-Kanpur",
#     "Mathura Bazar 1-Balrampur",
#     "Mau Ranipur-Jhansi",
#     "Mau Rural-Jhansi [Offline]",
#     "Medilalpurva Baharaich",
#     "Meerut Road Ghaziabad",
#     "MG Road Ghaziabad",
#     "Mihinpurwa-Bahraich",
#     "Milkipur-Faizabad",
#     "Moth-Jhansi [Offline]",
#     "Mughalsarai - Chandauli [Offline]",
#     "Mukimpur-Sitapur [Offline]",
#     "Muradpur -Sitapur",
#     "Nai Basti Bahraich",
#     "Naipura-Barabanki",
#     "Nazirpura-Bahraich",
#     "Nehru Nagar- Chandauli [Offline]",
#     "Nurwaf Mohalla Tikaitnagar",
#     "Om Shanti Nagar Jhansi",
#     "Pahadpur-Sitapur",
#     "Paigwa-Barabanki",
#     "Paisar Barabanki",
#     "Palhari Barabanki",
#     "Pandeypur- Varanasi [Offline]",
#     "Panki CF- Kanpur [Offline]",
#     "Panki- Kanpur [Offline]",
#     "Patel Nagar Fatehpur [Offline]",
#     "Pathauli-Agra",
#     "Prem Nagar Jhansi",
#     "Puraini-Bahraich",
#     "Qazipura-Bahraich [Offline]",
#     "Raj Nagar-Ghaziabad",
#     "Raja Bazar Nanpara",
#     "Ram Bagh Agra",
#     "Ramuapur Mahmoodabad",
#     "Rano Pali-Faizabad [Offline]",
#     "Rishibhumi Risia",
#     "Sahadatganj Faizabad",
#     "Sahdipur-Sitapur",
#     "Sahibabad Industrial Area-Ghaziabad [Offline]",
#     "Sai-Fatehpur",
#     "Samariya-Bahraich [Offline]",
#     "Samneghat- Varanasi [Offline]",
#     "Sanjay Nagar- Chandauli City [Offline]",
#     "Sarang Talab - Varanasi [Offline]",
#     "Saraswati Nagar Risiya",
#     "Sarnath - Varanasi [Offline]",
#     "Sarsa-Bahraich [Offline]",
#     "Sarwangi Mohalla Tikaitnagar",
#     "Shahabganj - Chandauli",
#     "Sharda Nagar Faizabad",
#     "Shastri Nagar-Kanpur [Offline]",
#     "Shivpur-Varanasi [Offline]",
#     "Sidhauli Town",
#     "Sikandarabad - Sitapur",
#     "Sikandra Agra",
#     "Sonarpura Varanasi [Offline]",
#     "Sundarpur - Varanasi [Offline]",
#     "Swaroop Nagar - Kanpur [Offline]",
#     "Taj East Gate Road Agra [Offline]",
#     "Takia Jarwal Kasba",
#     "Tap Sipaha-Barabanki",
#     "Tarinpur Sitapur",
#     "Tedwadih- Sitapur",
#     "Thangaon-Sitapur",
#     "Topri-Saharanpur[Offline]",
#     "UPSIDC Site C Agra",
#     "Veerangana nagar-Jhansi [Offline]",
#     "Vijay Laxmi Nagar Sitapur",
#     "Vikas Nagar- Kanpur",
#     "Vikas Nagar- Lucknow [Offline]",
#     "Vinod Vihar Colony Saharanpur [Offline]",
#     "Baldirai (E)-Sultanpur",
#     "Baldirai (W)-Sultanpur",
#     "Bikwajipur Parasin-Sultanpur",
#     "Bikwajipur-Sultanpur",
#     "Dhanaudi (E)-Sultanpur",
#     "Dhanaudi (W)-Sultanpur",
#     "Kharsoma (E) -Sultanpur",
#     "Kharsoma (N) Sultanpur",
#     "Kharsoma (S)-Sultanpur",
#     "Kharsoma (W) -Sultanpur",
#     "Paraspatti (E)-Sultanpur",
#     "Paraspatti (W)-Sultanpur",
#     "Purehubba-Sultanpur",
#     "Sukhbaderi-Sultanpur",
#     "Tiwaripur (E)-Sultanpur",
#     "Tiwaripur (W)-Sultanpur",
#     "Uttardah-Sultanpur",
# ]
